[CMake] Cleaning on the project and one scene
SofaDefrost/plugin.Cosserat pull request #65
Opened 2023-02-03 09:43 UTC by hugtalbot

It would be nice to rename the GitHub repository as "Cosserat" (without "plugin.") .

What do you think about this PR @adagolodjo ?

2023-02-03 15:37 UTC, adagolodjo commented on CMakeLists.txt
> +        TARGET_DIRECTORY softrobots
`cosserat` instead of `softrobots`, right ?

2023-02-03 15:39 UTC, adagolodjo commented
Hey @alxbilger, any suggestions on this? 
Tkx @hugtalbot

2023-02-06 08:37 UTC, alxbilger requested changes
you should also have a look in `initCosseratPlugin.cpp`. 
You could also add the following code in `config.h.in`:
```
namespace cosserat
{
	constexpr const char* MODULE_NAME = "@PROJECT_NAME@";
	constexpr const char* MODULE_VERSION = "@PROJECT_VERSION@";
}
```
to use the variables in `initCosseratPlugin.cpp`.

And I don't know what to do with `PythonEnvironment::addPythonModulePathsForPluginsByName("CosseratPlugin");`

2023-02-06 11:59 UTC, damienmarchal commented
> you should also have a look in `initCosseratPlugin.cpp`. You could also add the following code in `config.h.in`:
> 
> ```
> namespace cosserat
> {
> 	constexpr const char* MODULE_NAME = "@PROJECT_NAME@";
> 	constexpr const char* MODULE_VERSION = "@PROJECT_VERSION@";
> }
> ```
> 
> to use the variables in `initCosseratPlugin.cpp`.
> 
> And I don't know what to do with `PythonEnvironment::addPythonModulePathsForPluginsByName("CosseratPlugin");`

I don't know either, it depend what is the status of the deployement done by Guillaume. That line was to add to the python interpreter the path for python module that is just "next" to the loaded plugin. 

The idea was to be able to ship a plugin with this kind of structure:
```console
CosseratPlugin/
     - libCosseratPlugin.so (or .dll)
     - python3/cosserat
```
So that ones can do "import cosserat" easily.

2023-05-10 14:04 UTC, alxbilger commented
The only references to the old name `CosseratPlugin` are:

- `import Sofa.CosseratPlugin` in some scenes
- `PythonEnvironment::addPythonModulePathsForPluginsByName("CosseratPlugin");`
- `PYBIND11_MODULE(CosseratPlugin, m)`

and I don't know what to do with them. @damienmarchal ?

After that, the PR will be ready

2023-07-11 08:49 UTC, closed without merging